version: "3.8"

volumes:
  esdata:
  kibanadata:
  logstashdata:
  filebeatdata:
  nginx-logs:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    volumes:
      - "kibanadata:/usr/share/kibana/data"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.4
    ports:
      - "5044:5044/udp"
    volumes:
      - "logstashdata:/usr/share/logstash/data"
      - "./deploy/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
      - "nginx-logs:/var/log/nginx/:ro"
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_HOSTS=http://elasticsearch:9200

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.4
    volumes:
      - "filebeatdata:/usr/share/filebeat/data"
      - "./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "nginx-logs:/var/log/nginx/:ro"
    environment:
      - LOGSTASH_HOSTS=logstash:5045

  app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./app:/code"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

  nginx:
    image: nginx:1.19.2
    volumes:
      - "./deploy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./deploy/etc/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "nginx-logs:/var/log/nginx/"
    depends_on:
      - app
    ports:
      - "8080:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: nginx-docker
